apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  namespace: redis
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  replicas: 4
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
        location: prod

